### ISSUE TITLE
Keyboard covering parts of the app when editing the title of an entry

### ISSUE THREAD

**Issue by GitHorst** [douzifly/clear-todolist#13] opened 2016-02-21 18:51 UTC
case 1) When you edit the title of an item, the part where you can set the time for the reminder is covered by the keyboard popping up.

case 2) While still in title editing mode: clicking on the "back" arrow does not hide the keyboard, which will then cover the list of items.

**Comment by odysseusPolytropos** [comment] 2016-03-18 00:19
This seems to be fixed by version 1.5.6. At least I'm unable to reproduce it with Android 6 and AOSP-Keyboard.

**Closed as completed** 2022-03-07 10:07 UTC
